"""empty message

Revision ID: cd788e66518d
Revises: 59abbf1f4b90
Create Date: 2020-06-01 15:50:00.213195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd788e66518d'
down_revision = '59abbf1f4b90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'genres')
    op.add_column('artist', sa.Column('genres', sa.ARRAY(sa.VARCHAR(length=120)), nullable=True))
    op.drop_column('venue', 'genres')
    op.add_column('venue', sa.Column('genres', sa.ARRAY(sa.VARCHAR(length=120)), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venue', 'genres',
               type_=sa.VARCHAR(),
               nullable=True)
    op.alter_column('artist', 'genres',
               type_=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
